"""Rename duration_minutes to duration_seconds and convert to seconds

Revision ID: 0b6113558d08
Revises: 
Create Date: 2025-10-29 00:07:13.836945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6113558d08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_playbacks_content_episode', 'playbacks', ['content_id', 'episode_id'], unique=False)
    op.create_index('ix_playbacks_profile_started', 'playbacks', ['profile_id', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_playbacks_profile_started', table_name='playbacks')
    op.drop_index('ix_playbacks_content_episode', table_name='playbacks')
    # ### end Alembic commands ###
