"""finalize_plans_model

Revision ID: 0cf375d19bd5
Revises: 2363b04eebed
Create Date: 2025-09-30 16:15:27.620167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf375d19bd5'
down_revision: Union[str, Sequence[str], None] = '2363b04eebed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.drop_column('profiles', 'avatar_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('avatar_url', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'avatar')
    # ### end Alembic commands ###
