"""finalize_plans_model

Revision ID: 11673f184d81
Revises: 71907498564b
Create Date: 2025-09-30 15:58:41.339332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11673f184d81'
down_revision: Union[str, Sequence[str], None] = '71907498564b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('MOVIE', 'SERIES', name='content_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('age_rating', sa.String(length=10), nullable=True),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('actualizado_por', sa.UUID(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contents_actualizado_por'), 'contents', ['actualizado_por'], unique=False)
    op.create_index(op.f('ix_contents_creado_por'), 'contents', ['creado_por'], unique=False)
    op.create_index(op.f('ix_contents_title'), 'contents', ['title'], unique=False)
    op.create_table('episodes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('actualizado_por', sa.UUID(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodes_actualizado_por'), 'episodes', ['actualizado_por'], unique=False)
    op.create_index(op.f('ix_episodes_content_id'), 'episodes', ['content_id'], unique=False)
    op.create_index(op.f('ix_episodes_creado_por'), 'episodes', ['creado_por'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('actualizado_por', sa.UUID(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_actualizado_por'), 'watchlists', ['actualizado_por'], unique=False)
    op.create_index(op.f('ix_watchlists_content_id'), 'watchlists', ['content_id'], unique=False)
    op.create_index(op.f('ix_watchlists_creado_por'), 'watchlists', ['creado_por'], unique=False)
    op.create_index(op.f('ix_watchlists_profile_id'), 'watchlists', ['profile_id'], unique=False)
    op.create_table('playbacks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('device', sa.String(length=80), nullable=True),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('actualizado_por', sa.UUID(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playbacks_actualizado_por'), 'playbacks', ['actualizado_por'], unique=False)
    op.create_index(op.f('ix_playbacks_content_id'), 'playbacks', ['content_id'], unique=False)
    op.create_index(op.f('ix_playbacks_creado_por'), 'playbacks', ['creado_por'], unique=False)
    op.create_index(op.f('ix_playbacks_episode_id'), 'playbacks', ['episode_id'], unique=False)
    op.create_index(op.f('ix_playbacks_profile_id'), 'playbacks', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playbacks_profile_id'), table_name='playbacks')
    op.drop_index(op.f('ix_playbacks_episode_id'), table_name='playbacks')
    op.drop_index(op.f('ix_playbacks_creado_por'), table_name='playbacks')
    op.drop_index(op.f('ix_playbacks_content_id'), table_name='playbacks')
    op.drop_index(op.f('ix_playbacks_actualizado_por'), table_name='playbacks')
    op.drop_table('playbacks')
    op.drop_index(op.f('ix_watchlists_profile_id'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_creado_por'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_content_id'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_actualizado_por'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_episodes_creado_por'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_content_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_actualizado_por'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_contents_title'), table_name='contents')
    op.drop_index(op.f('ix_contents_creado_por'), table_name='contents')
    op.drop_index(op.f('ix_contents_actualizado_por'), table_name='contents')
    op.drop_table('contents')
    # ### end Alembic commands ###
