"""improve profile management

Revision ID: 1a159f2a051d
Revises: 
Create Date: 2025-11-08 14:00:48.109600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a159f2a051d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_watchlists_profile_content', 'watchlists', ['profile_id', 'content_id'], unique=False)
    op.create_unique_constraint('uq_watchlists_profile_content', 'watchlists', ['profile_id', 'content_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_watchlists_profile_content', 'watchlists', type_='unique')
    op.drop_index('ix_watchlists_profile_content', table_name='watchlists')
    # ### end Alembic commands ###
