"""add_unique_constraint_and_index_to_watchlists

Revision ID: 40f660ecbe7a
Revises: b0f92e7a84c6
Create Date: 2025-11-04 11:12:49.419172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f660ecbe7a'
down_revision: Union[str, Sequence[str], None] = 'b0f92e7a84c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_watchlists_profile_content', 'watchlists', ['profile_id', 'content_id'], unique=False)
    op.create_unique_constraint('uq_watchlists_profile_content', 'watchlists', ['profile_id', 'content_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_watchlists_profile_content', 'watchlists', type_='unique')
    op.drop_index('ix_watchlists_profile_content', table_name='watchlists')
    # ### end Alembic commands ###
