"""add_user_id_to_profile_list_item_schema

Revision ID: 5f7a0148f9ff
Revises: e144aed82f76
Create Date: 2025-10-24 23:31:05.336837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f7a0148f9ff'
down_revision: Union[str, Sequence[str], None] = 'e144aed82f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
