"""create relations

Revision ID: 7d9de1e29b0d
Revises: 5d70ffbdd736
Create Date: 2025-09-30 15:33:58.645045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9de1e29b0d'
down_revision: Union[str, Sequence[str], None] = '5d70ffbdd736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_profiles', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('max_devices', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('video_quality', sa.String(length=20), server_default=sa.text("'HD'"), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('actualizado_por', sa.UUID(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_plans_actualizado_por'), 'plans', ['actualizado_por'], unique=False)
    op.create_index(op.f('ix_plans_creado_por'), 'plans', ['creado_por'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='payment_status'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('actualizado_por', sa.UUID(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_actualizado_por'), 'payments', ['actualizado_por'], unique=False)
    op.create_index(op.f('ix_payments_creado_por'), 'payments', ['creado_por'], unique=False)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.add_column('profiles', sa.Column('name', sa.String(length=60), nullable=False))
    op.add_column('subscriptions', sa.Column('plan_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_foreign_key(None, 'subscriptions', 'plans', ['plan_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_column('subscriptions', 'plan_id')
    op.drop_column('profiles', 'name')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_creado_por'), table_name='payments')
    op.drop_index(op.f('ix_payments_actualizado_por'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_plans_creado_por'), table_name='plans')
    op.drop_index(op.f('ix_plans_actualizado_por'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
