"""Rename duration_minutes to duration_seconds and convert to seconds

Revision ID: 930a8d0ee524
Revises: 
Create Date: 2025-10-28 23:48:29.866596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '930a8d0ee524'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.drop_column('contents', 'duration_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('contents', 'duration_seconds')
    # ### end Alembic commands ###
