"""Rename duration_minutes to duration_seconds and convert to seconds

Revision ID: ae90561411fb
Revises: 
Create Date: 2025-10-28 23:35:15.611052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae90561411fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playbacks_profile_started'), table_name='playbacks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_playbacks_profile_started'), 'playbacks', ['profile_id', 'started_at'], unique=False)
    # ### end Alembic commands ###
