"""improve playback table

Revision ID: bb9e64749e17
Revises: 
Create Date: 2025-11-07 15:09:53.025218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb9e64749e17'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_active_playback', 'playbacks', ['profile_id', 'device', 'content_id', 'episode_id'], unique=True, postgresql_where=sa.text('completed = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_playback', table_name='playbacks', postgresql_where=sa.text('completed = false'))
    # ### end Alembic commands ###
